---
title: "Cognitive processes diagram"
author: "Einat R."
date: "15/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DiagrammeR)
```


```{r cognitive processes diagram 1, echo=FALSE, fig.cap="Fig.1. This diagram represents the cognitive processes we hypothesize about in our study. *Target selection* means whatever processes the N2pc reflects, and *WM*  means whatever processes the SPCN reflects. *Post selection processes* means whatever processes the RLpcN reflects. Middle row shows processing stages from the start of a trial until a response is given. Bottom row indicates the factors hypothesized to affect certain stages, which are indicated by the arrows. *task* refers to discimination vs compound, so it's not a complete overlap with *response mapping*."}

grViz("
digraph cognitive_processes {
# a 'graph' statement
graph [overlap = true, fontsize = 10, rankdir = BT]
node [shape = box,
        fontname = Helvetica]

subgraph {
rank = same; 1; 2; 3; 4; 5;
}
subgraph {
rank = same; 6; 7; 13;
}
subgraph {
rank = same; 8; 9; 10; 11; 12;
}

1 [label = search]
2 [label = attentional_engagement]
3 [label = target_processing]
4 [label = response_selection]
5 [label = response_execution]
6 [label = target_selection]
7 [label = WM]
8 [label = cue]
9 [label = target_salience]
10 [label = distractor_presence]
11 [label = task]
12 [label = response_mapping]
13 [label = post_selection_processes]

1->2; 2->3; 3->4; 4->5;
8->1; 9->{1 3}; 10->{1 3}; 12->{4 5};
11->3; 
3->7;
4->7;
2->6;
3->6;
3->13;
4->13;
5->13;

}
")
```
